### Sebastián Rodríguez
### 20003076

# Práctica 5 - Forward propagation y análisis de representaciones intermedias

In [4]:
import numpy as np
import matplotlib.pyplot as plt

# Primer Diagrama

In [6]:
def sigmoide(X):
  return 1/(1+np.exp(-X))
def Activacion(z):
    return (z >= 0).astype(np.float)
Activacion(np.array([1]))
def Transf(x, Pesos):
    return np.matmul(x, Pesos)

In [7]:
sigmoide(np.array([2,3,4]))

array([0.88079708, 0.95257413, 0.98201379])

In [12]:
Peso1 = np.array([[0.9,0.8,0.1],[0.3,0.5,0.6],[0.2,0.4,0.7]])

Peso2 = np.array([0.3,0.5,0.9])

X = np.array([[1,0,1],[1,2,3],[4,5,6],[6,7,8],])

In [10]:
H = np.matmul(X,Peso1)
A = sigmoide(H)


In [14]:
Aprox_Sal = sigmoide(np.matmul(A,Peso2))
Aprox_Sal

array([0.77387413, 0.83403412, 0.84538425, 0.84552612])

In [15]:
def g(X):
  return sigmoide(np.matmul(X,Peso1))

  
def f(g):
  return sigmoide(np.matmul(g,Peso2))

In [16]:
Aprox_Sal = f(g(X))
Aprox_Sal

array([0.77387413, 0.83403412, 0.84538425, 0.84552612])

# Segundo Diagrama

In [22]:
class RedNeuronal:
  def __init__(self):
    self.Peso1 = np.array([[0.8,0.2],[0.4,0.9],[0.3,0.5]])
    self. Peso2  = np.array([0.3,0.5,0.9])

  def For_Prop(self,X):
    print(X.shape)
    print(self.Peso1.T.shape)
    A = sigmoide(np.matmul(X,self.Peso1.T))
    print(A)
    print(A.shape)
    Aprox_Sal = sigmoide(np.matmul(A,self.Peso2)) 
    print(Aprox_Sal.shape)
    return Aprox_Sal

In [23]:
X = np.array([[1,1],[1,2],[4,5],[6,7],])
red = RedNeuronal()
Aprox_Sal = red.For_Prop(X)
#Aprox_Sal

(4, 2)
(2, 3)
[[0.73105858 0.78583498 0.68997448]
 [0.76852478 0.90024951 0.78583498]
 [0.98522597 0.99776215 0.97587298]
 [0.99797468 0.99983344 0.9950332 ]]
(4, 3)
(4,)


# Tercer Diagrama

In [33]:
def Heavyside(x):
    return (x >= 0).astype(np.float)

def Bias(x):
    return np.vstack((x, np.ones(x.shape[1])))


In [28]:
x = np.array([1, 0]).reshape(-1, 1)
Peso1 = np.array([[20., 20., -10.], [-20., -20., 30.]])
M1M = np.matmul(Peso1, Bias(x))
Act1 = Heavyside(M1M)
Peso2 = np.array([[20, 20, -30]])
M2M = np.matmul(Peso2, Bias(Act1))
Act2 = Heavyside(M2M)

In [29]:
def F_XOR(x, activation=Heavyside, retHidden=False):

    Peso1 = np.array([[20., 20., -10.], [-20., -20., 30.]])
    Peso2 = np.array([[20, 20, -30]])
    M1M = np.matmul(Peso1, Bias(x))
    Act1 = activation(M1M)
    M2M = np.matmul(Peso2, Bias(Act1))
    y = activation(M2M)    
    if retHidden:
        return y, Act1
    return y

In [31]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
X = X.T
X, X.shape

(array([[0, 0, 1, 1],
        [0, 1, 0, 1]]), (2, 4))

In [32]:
F_XOR(X)
F_XOR(X, activation=sigmoide)

array([[4.54391049e-05, 9.99954520e-01, 9.99954520e-01, 4.54391049e-05]])